apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: webappcolor-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp-color
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 5